<!DOCTYPE html>
<html>
<head>
    <title> MEU CEP </title>
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body> 
    <header class="header-top">
        <h1>MEU CEP</h1>
    </header>
    
    <section class="container-box">
        <header class="container-box-primary">
            <h3>Qual endereço você deseja buscar?</h3>
        </header>
        
        <section class="container-box-secondary">
            <form action="index.php" method="post" class="form-cep">
		        <input type="text" name="cep" placeholder="Insira o CEP">
		        <input type="submit" value="Enviar">
            </form>
        </section>
<?php
    if(!empty($this->getDatas())){

?>

        <section class="container-dt">
            <section class="dt-left">
                <img src='imgs/icon-address.png' />
            </section>
            <aside class="dt-right">
                <div class="datas">
                    <h5 class="text-uppercase text-muted ls-1 mb-1">
                          CEP
                    </h5>
                    <h2 class="mb-0"><?php echo $this->getDatas()->cep; ?></h2>
                </div>
                <div class="datas">
                    <h5 class="text-uppercase text-muted ls-1 mb-1">
                          Rua
                    </h5>
                    <h2 class="mb-0"><?php echo $this->getDatas()->logradouro; ?></h2>
                </div>
                <div class="datas">
                    <h5 class="text-uppercase text-muted ls-1 mb-1">
                          Bairro
                    </h5>
                    <h2 class="mb-0"><?php echo $this->getDatas()->bairro; ?></h2>
                </div>
                <div class="datas">
                    <h5 class="text-uppercase text-muted ls-1 mb-1">
                          Estado
                    </h5>
                    <h2 class="mb-0"><?php echo $this->getDatas()->uf; ?></h2>
                </div>
            </aside>
        </section>
<?php
    }
?>
    </section>
</body>
</html>

